cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'zsh'
brew 'coreutils'
brew 'cmake'
brew 'grc'
brew 'go'
brew 'jq'
brew 'readline'
brew 'wget'
brew 'vim', args: ["with-override-system-vi", "with-lua"]
brew 'autoenv'
brew 'awscli'
brew 'zsh-git-prompt'
brew 'jsonlint'
brew 'proselint'
brew 'nvm'
brew 'tree'
brew 'watch'
brew 'packer'
brew 'azure-cli'
brew 'kubernetes-cli'
brew 'kops'
brew 'cfssl'
brew 'kubernetes-helm'
brew 'kubectx'
brew 'kube-ps1'
brew 'vault'
brew 'watchman'
brew 'terraform'

#Telepresence https://www.telepresence.io/reference/install
brew 'socat'
cask 'osxfuse'
tap 'datawire/blackbird'
brew 'datawire/blackbird/telepresence'

#Draft: https://github.com/Azure/draft
tap 'azure/draft'
brew 'draft'

cask 'authy'
cask 'slack'
cask 'steam'
cask 'viscosity'
cask 'kaleidoscope'
#cask 'docker'
cask 'iterm2'
cask 'arq'
cask 'mist'
cask 'transmit'
cask 'transmit-disk'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'insomnia'
cask 'minikube'
cask 'visual-studio-code'


