-- [nfnl] Compiled from lua/mappings.fnl by https://github.com/Olical/nfnl, do not edit.
local u = require("util")
local function create_keymaps()
  u.lnnoremap(".", "ToggleTerm", "toggle terminal")
  vim.keymap.set("t", "<esc><esc>", "<c-\\><c-n>", {noremap = true})
  u.lnnoremap("wh", "wincmd h", "window left")
  u.lnnoremap("wj", "wincmd j", "window down")
  u.lnnoremap("wk", "wincmd k", "window up")
  u.lnnoremap("wl", "wincmd l", "window right")
  u.lnnoremap("w1", "1 wincmd w", "window 1")
  u.lnnoremap("w2", "2 wincmd w", "window 2")
  u.lnnoremap("w3", "3 wincmd w", "window 3")
  u.lnnoremap("w4", "4 wincmd w", "window 4")
  u.lnnoremap("w5", "5 wincmd w", "window 5")
  u.lnnoremap("w6", "6 wincmd w", "window 6")
  u.lnnoremap("wm", "only", "close other windows")
  u.lnnoremap("wn", "split", "split current window (horizontal)")
  u.lnnoremap("w|", "vsplit", "split current window (vertical)")
  u.lnnoremap("wq", "close", "close current window")
  u.lnnoremap("<tab>", "b#", "next buffer")
  u.lnnoremap("ba", "ball", "open all buffers")
  u.lnnoremap("bb", "Telescope buffers", "list buffers")
  u.lnnoremap("bd", "bdelete", "delete current buffer")
  u.lnnoremap("bn", "bnext", "next buffer")
  u.lnnoremap("bp", "bprevious", "previous buffer")
  u.lnnoremap("f/", "Telescope live_grep", "grep in workspace")
  u.lnnoremap("fb", "Telescope file_browser", "browse project")
  u.lnnoremap("ff", "Telescope find_files", "project files")
  u.lnnoremap("fs", "write")
  u.lnnoremap("ft", "NvimTreeToggle", "toggle file tree")
  u.lnnoremap("pt", "TodoTelescope", "project todos")
  u.lnnoremap("pp", "lua require'telescope'.extensions.project.project{ display_type = 'full' }", "projects")
  u.lnnoremap("Pl", "Lazy", "open plugin manager (lazy.nvim)")
  u.lnnoremap("gb", "Gitsigns toggle_current_line_blame", "toggle git blame")
  u.lnnoremap("gs", "Telescope git_status", "git status")
  u.lnnoremap("gl", "Telescope git_commits", "git log")
  return u.lnnoremap("et", "TroubleToggle", "toggle error view")
end
return {create_keymaps = create_keymaps}
