# shortcut to this dotfiles path is $ZSH
export ZSH=$HOME/.dotfiles

# project folder that we can `c [tab]` to
export PROJECTS=~/workspace

# all of our zsh files
typeset -U config_files
config_files=($ZSH/**/*.zsh)

# load the path files
for file in ${(M)config_files:#*/path.zsh}
do
  source $file
done

# source *.zsh files explicity (other than path.zsh)
source ~/.dotfiles/zsh/aliases.zsh
source ~/.dotfiles/zsh/window.zsh
source ~/.dotfiles/zsh/prompt.zsh
source ~/.dotfiles/zsh/editor.zsh
source ~/.dotfiles/zsh/config.zsh
source ~/.dotfiles/zsh/zoxide.zsh

source ~/.dotfiles/iterm/shell_integration.zsh
source ~/.dotfiles/git/aliases.zsh
source ~/.dotfiles/nvm/nvm.zsh
source ~/.dotfiles/java/jenv.zsh
source ~/.dotfiles/java/java.zsh

# completion
source ~/.dotfiles/zsh/completion.zsh

unset config_files
bindkey -v
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Better history
# Credits to https://coderwall.com/p/jpj_6q/zsh-better-history-searching-with-arrow-keys
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey -M vicmd 'k' up-line-or-beginning-search # Up
bindkey -M vicmd 'j' down-line-or-beginning-search # Down
bindkey -M vicmd '?' history-incremental-search-backward

# shift-tab to go back in autocomplete menus
bindkey '^[[Z' reverse-menu-complete 

PATH=$PATH:$HOME/.local/bin:$HOME/workspace/bin:
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

eval "$(direnv hook zsh)"

# SSH Agent remote
if [ -z $SSH_TTY ]; then
  SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
fi

# remote browser open forwarding see: https://github.com/superbrothers/opener

if [ -n "$SSH_TTY" ]; then
  export BROWSER=~/bin/open
fi

# Stash your environment variables in ~/.localrc. This means they'll stay out
# of your main dotfiles repository (which may be public, like this one), but
# you'll have access to them in your scripts.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# RAZOR SHELL-UTILITIES
